# Ficha 5

In [1]:
# Miguel Saraiva Grilo
# 58387                       IACD

In [2]:
import os
print('O ficheiro está na pasta: ', os.getcwd())
import datetime
date = datetime.datetime.now()
print( "Hoje: {:%d/%m/%Y %H:%M:%S\n}".format(date))

O ficheiro está na pasta:  /home/miguelgrilo/UNI-L58387-IACD/S2-LME/Estudos
Hoje: 20/04/2024 00:28:21



## Numpy



### Recorde que deve:


* *Visitar* o site oficial https://numpy.org para aceder a toda a informação sobre a **Numpy**.

* <u>**Explorar**</u> a informação que pode encontrar na página 
https://numpy.org/doc/stable/numpy-user.pdf para recordar a descrição e operacionalidades de comandos.

* <u>**Recorrer**</u> sempre que necessário ao 
[tutorial](https://numpy.org/numpy-tutorials/).

* Utilizar o ***help*** para uma consulta rápida sobre sintaxe dos comandos.

* Utilizar o ***dir*** para uma consulta rápida sobre as classes e os comandos da biblioteca.

* Visitar o site http://www.python.org para obter informação adicional, demonstrações e suporte sobre a linguagem *Python*. 

* Visitar o site https://jupyter.org para informações sobre o interpretador *Jupyter*. 

### Importe a biblioteca Numpy

In [3]:
import numpy as np

### Criação de Arrays:
https://numpy.org/doc/stable/reference/routines.array-creation.html

**Execute e analise os resultados:**

# ============================================

### Exercício 1  

Considere $A=\left[\begin{array}{ccc}
1&2&3&4\\
5&6&7&8
\end{array}
\right]$ e
$b =[0, 9]^T$. 

1. Com o comando array defina $A$ e $b$
1. Verifique que estes arrays são do tipo numpy.ndarray
1. O comando seguinte
    `print([x for x in dir(b) if not x.startswith('_')])`
    permite-lhe visualizar todos os atributos do array $b$. Execute-o. Adapte este comando ao array $A$.
    
    1. Aplique a $A$ e $b$ os atributos *shape, *size*,*ndim*, *itemsize* e *nbytes*. Após analisar os resultados, coloque comentários, explicando o significado destes atributos.
    1. Calcule a matriz $C=A^TA$.
    1. Repita a alínea A. para a matriz $C$.
    1. Calcule $b^T$. Verique se o resultado foi o esperado. Comente.

**Nota:**
> Utilizando o **help** pode também se inteirar sobre os atributos de *ndarray*. Verifique

 

In [4]:
#Alínea 1
A=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b=np.array([[0, 9]]).T
display(A, b)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([[0],
       [9]])

In [5]:
#Alínea 2
print(isinstance(A, np.ndarray))
print(isinstance(b, np.ndarray))

True
True


In [6]:
#Alínea 3
print([x for x in dir(b) if not x.startswith('_')],"\n")
print([x for x in dir(A) if not x.startswith('_')])

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'] 

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemse

In [7]:
#Item A
print("A:\nShape:", A.shape)      #Matriz A com 2 linhas e 4 colunas
print("Size:", A.size)            #Número de elementos em A é 8
print("Ndim:", A.ndim)            #Número de dimensões em A é 2
print("Itemsize:", A.itemsize)    #Tamanho de cada item em A é 8 bytes
print("Nbytes:", A.nbytes)        #Espaço ocupado por A é 64 bytes

print("\nb:\nShape:", b.shape)    #Matriz b com 2 linhas e 1 coluna 
print("Size:", b.size)            #Número de elementos em b é 2
print("Ndim:", b.ndim)            #Número de dimensões em b é 2
print("Itemsize:", b.itemsize)    #Tamanho de cada item em b é 8 bytes
print("Nbytes:", b.nbytes)        #Espaço ocupado por b é 16 bytes

A:
Shape: (2, 4)
Size: 8
Ndim: 2
Itemsize: 8
Nbytes: 64

b:
Shape: (2, 1)
Size: 2
Ndim: 2
Itemsize: 8
Nbytes: 16


In [8]:
#Item B
C=np.dot(A.T, A)
display(C)

array([[26, 32, 38, 44],
       [32, 40, 48, 56],
       [38, 48, 58, 68],
       [44, 56, 68, 80]])

In [9]:
#Item C
print("C:\nShape:", C.shape)      #Matriz C com 4 linhas e 4 colunas
print("Size:", C.size)            #Número de elementos em C é 16
print("Ndim:", C.ndim)            #Número de dimensões em C é 2
print("Itemsize:", C.itemsize)    #Tamanho de cada item em C é 8 bytes
print("Nbytes:", C.nbytes)        #Espaço ocupado por C é 128 bytes

C:
Shape: (4, 4)
Size: 16
Ndim: 2
Itemsize: 8
Nbytes: 128


In [10]:
#Item D
b_T = b.T
display(b_T)
#Sim, o resultado foi o esperado. Para que este cálculo retornasse correto foi necessário
#utilizar os '[]' duas vezes, para informar o computador de que se tratava de uma matriz.

array([[0, 9]])

# ============================================

### Exercício 2  

Podemos criar um array de vários tipos, definindo o array com a opção dtype que pode assumir os seguintes tipos:

`dtype = 'int32', 'int64', 'int', 'float' ,'complex','str','bool',... `

Crie um ciclo for para definir e visualizar o array 
$A=\left[\begin{array}{ccc}
1&2&3\\
5&6&7
\end{array}
\right]$ com os diferentes tipos. Para cada tipo diferente do array determine a dimensão e a memória ocupada por cada elemento do array. Comente.

In [11]:
#Alínea 2
valores=[[1, 2, 3], [5, 6, 7]]
dtype=['int32', 'int64', 'float32', 'float64', 'complex64', 'complex128', 'str', 'bool']
for dtype in dtype:
    A=np.array(valores, dtype=dtype)
    print("\nTipo de Dados:", dtype)
    print("Array A:\n", A)
    #display(A)
    print("Dimensão de A:", A.ndim)
    print("Espaço ocupado por cada elemento de A:", A.itemsize)


Tipo de Dados: int32
Array A:
 [[1 2 3]
 [5 6 7]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 4

Tipo de Dados: int64
Array A:
 [[1 2 3]
 [5 6 7]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 8

Tipo de Dados: float32
Array A:
 [[1. 2. 3.]
 [5. 6. 7.]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 4

Tipo de Dados: float64
Array A:
 [[1. 2. 3.]
 [5. 6. 7.]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 8

Tipo de Dados: complex64
Array A:
 [[1.+0.j 2.+0.j 3.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 8

Tipo de Dados: complex128
Array A:
 [[1.+0.j 2.+0.j 3.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 16

Tipo de Dados: str
Array A:
 [['1' '2' '3']
 ['5' '6' '7']]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 4

Tipo de Dados: bool
Array A:
 [[ True  True  True]
 [ True  True  True]]
Dimensão de A: 2
Espaço ocupado por cada elemento de A: 1


# ============================================

### Exercício 3 

1. Crie um array vazio de dimensão $4\times 3$, do tipo inteiro.
1. Crie um array nulo de dimensão $4\times 3$, do tipo inteiro.
1. Crie um array de componentes iguais a 1 de dimensão $3\times 3$, do tipo inteiro.
2. Crie uma matriz (array) diagonal com os elementos principais [2,3,4]. 
3. Crie uma matriz (array) identidade, de dimensão 4.

**Nota**
> Os comando usados neste exercício são comuns à biblioteca **Sympy**.

In [12]:
#Alínea 1
vazio=np.empty((4, 3), dtype=int)
print("Array vazio:\n", vazio)

Array vazio:
 [[4607182418800017408                   0 4611686018427387904]
 [                  0 4613937818241073152                   0]
 [4617315517961601024                   0 4618441417868443648]
 [                  0 4619567317775286272                   0]]


In [13]:
#Alínea 2
nulo=np.zeros((4, 3), dtype=int)
print("Array nulo:\n", nulo)

Array nulo:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
#Alínea 3
uns=np.ones((3, 3), dtype=int)
print("Array de uns:\n", uns)

Array de uns:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
#Alínea 4
diagonal=np.diag([2, 3, 4])
print("Array diagonal:\n", diagonal)

Array diagonal:
 [[2 0 0]
 [0 3 0]
 [0 0 4]]


In [16]:
#Alínea 5
identidade=np.eye(4)
print("Array identidade:\n", identidade)

Array identidade:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ============================================

### Exercício 4

1. Informe-se sobre o módulo random.
2. Crie um array bidimensional, à sua escolha, de números aleatórios entre 0 e 1.

In [17]:
#Alínea 1
##help(np.random)

In [18]:
#Alínea 2
aleatorio=np.random.rand(3,4)
print("Array aleatório:\n", aleatorio)

Array aleatório:
 [[0.88289285 0.33736745 0.56155398 0.38901035]
 [0.21123084 0.203223   0.80502942 0.23594696]
 [0.6131982  0.65521587 0.21045144 0.13657557]]


# ============================================
### Exercício 5  

1. Considere  $A=\left[ 
\begin{array}{ccc}
1 & -3 & 4 \\ 
8 & 11 & -1%
\end{array}%
\right] ,$  $B=\left[ 
\begin{array}{cc}
3 & 2 \\ 
-1 & 2 \\ 
2 & 4%
\end{array}%
\right] ,$  $C=\left[ 
\begin{array}{ccc}
3 & -1 & 4 \\ 
2 & -2 & 1 \\ 
-2 & 1 & 6%
\end{array}%
\right] $


e calcule:   
&emsp; &ensp; a) $(2A+B^T)C$   
&emsp; &ensp; b) $(C - 2I)^2$  

2. Crie o array $X = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]$ usando   
    a) a função `np.arange()`   
    b) a função `np.linspace()`

3.  Calcule  $\space 𝑎𝑟𝑐𝑡𝑎𝑛(𝑥), \space 𝑒^𝑥, \space 𝑙𝑛(𝑥), \space \sqrt x$ usando as funções do NumPy para os valores do array X

4) Execute o seguinte código e corrija o erro cometido:   
`import numpy as np
M = np*linspace(0,10)
Y = sin(M);      
print('Y=', Y)`


In [19]:
#Alínea 1
#Item A
A=np.array([[1, -3, 4], [8, 11, -1]])
B=np.array([[3, 2], [-1, 2], [2, 4]])
C=np.array([[3, -1, 4], [2, -2, 1], [-2, 1, 6]])
a=np.dot((2*A+B.T), C)
print(a)

[[-19  19  73]
 [ 98 -64 108]]


In [20]:
#Item B
I=np.eye(3)
b=np.dot((C-2*I), (C-2*I))
print(b)

[[-9.  7. 19.]
 [-8. 15.  8.]
 [-8.  2.  9.]]


In [21]:
#Alínea 2
#Item A
X=np.arange(1.0, 3.1, 0.25)
print(X)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.  ]


In [22]:
#Item B
X=np.linspace(1.0, 3.0, 9)
print(X)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.  ]


In [23]:
#Alínea 3
print("Arctan(X):\n", np.arctan(X))
print("Exp(X):\n", np.exp(X))
print("Log(X):\n", np.log(X))
print("Sqrt(X):\n", np.sqrt(X))

Arctan(X):
 [0.78539816 0.89605538 0.98279372 1.05165021 1.10714872 1.152572
 1.19028995 1.22202532 1.24904577]
Exp(X):
 [ 2.71828183  3.49034296  4.48168907  5.75460268  7.3890561   9.48773584
 12.18249396 15.64263188 20.08553692]
Log(X):
 [0.         0.22314355 0.40546511 0.55961579 0.69314718 0.81093022
 0.91629073 1.01160091 1.09861229]
Sqrt(X):
 [1.         1.11803399 1.22474487 1.32287566 1.41421356 1.5
 1.58113883 1.6583124  1.73205081]


In [24]:
#Alínea 4
import numpy as np
M=np.linspace(0,10)
Y=np.sin(M);
print('Y=', Y)

Y= [ 0.          0.20266794  0.39692415  0.57470604  0.72863478  0.85232157
  0.94063279  0.98990308  0.99808748  0.96484631  0.89155923  0.78126802
  0.63855032  0.46932961  0.2806294   0.08028167 -0.12339814 -0.32195632
 -0.50715171 -0.67129779 -0.80758169 -0.91034694 -0.97532829 -0.99982867
 -0.9828312  -0.92504137 -0.82885774 -0.6982724  -0.53870529 -0.35677924
 -0.16004509  0.04333173  0.24491007  0.43632343  0.6096272   0.75762842
  0.8741843   0.9544572   0.99511539  0.99447137  0.95255185  0.8710967
  0.75348673  0.60460332  0.43062587  0.23877532  0.0370144  -0.16628279
 -0.36267843 -0.54402111]


# ============================================
### Exercício 6

Considere a função $$f(x) = 1+e^{-0.2x}-x^{1.5}.$$

Para $i=1,...,9$, tais que $x_i \in X = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]$ calcule
$df(X) = [f^{(5)}(x_i)]$.

In [25]:
def f(x):
    return (1+np.exp(-0.2*x)-x**1.5)
X=np.arange(1.0, 3.1, 0.25)
ordem=5
df5=f(X)
for _ in range(ordem):
    df5 = np.gradient(df5, X)
print(df5)

[ 2.6543153   2.37601124 -0.60883643 -3.00081933 -0.46121752  1.67494155
 -0.05302247 -1.63947909 -1.5868537 ]


## ==============================================

# %%%%%%%%%%%%%%%%%%%%%%%%

In [26]:
# Executar este código no final do trabalho:
import datetime
date = datetime.datetime.now()
print("FIM:  {:%d/%m/%Y %H:%M:%S\n}".format(date))

FIM:  20/04/2024 00:28:21



# %%%%%%%%%%%%%%%%%%%%%%%%